//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedbacks
    {
        public int FeedbackId { get; set; }
        public Nullable<int> PatientId { get; set; }
        public Nullable<int> TherapistId { get; set; }
        public Nullable<int> Servicing { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Expertise { get; set; }
        public Nullable<System.DateTime> FeedbackDate { get; set; }
    
        public virtual Therapists Therapists { get; set; }
    }
}
