//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkHour
    {
        public int WorkHoursId { get; set; }
        public Nullable<int> TherapistId { get; set; }
        public string Day { get; set; }
        public string Hour { get; set; }
    
        public virtual Therapist Therapist { get; set; }
    }
}
